services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=api_user
      - DB_PASSWORD=api_password
      - DB_NAME=api_db
      - JWT_SECRET=tu_super_secreto_aqui
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=api_password
      - POSTGRES_DB=api_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api_user -d api_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5432" 

volumes:
  pg_data: