import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1747329865676 implements MigrationInterface {
    name = 'InitialSchema1747329865676'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "calendario_vacuna" ("id_calendario_vacuna" int NOT NULL IDENTITY(1,1), "edad_recomendada" int NOT NULL, "dosis" int NOT NULL, "etapa" nvarchar(50), "id_vacuna" int, CONSTRAINT "PK_a40f4b098948760e4f5ef6ab1b4" PRIMARY KEY ("id_calendario_vacuna"))`);
        await queryRunner.query(`CREATE TABLE "programa_control" ("id_programa_control" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(100) NOT NULL, "descripcion" nvarchar(255), "activo" nvarchar(1) NOT NULL, "codigo" nvarchar(10) NOT NULL, CONSTRAINT "UQ_be101730276807dea95d4869114" UNIQUE ("codigo"), CONSTRAINT "PK_ee15c4fdb48fa4f996103ee855c" PRIMARY KEY ("id_programa_control"))`);
        await queryRunner.query(`CREATE TABLE "rol" ("id_rol" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(100) NOT NULL, "descripcion" text, CONSTRAINT "UQ_9792c580a992d554ee1621c5b45" UNIQUE ("nombre"), CONSTRAINT "PK_0b42a30072d57ccfad9949218da" PRIMARY KEY ("id_rol"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id_usuario" int NOT NULL IDENTITY(1,1), "username" nvarchar(50) NOT NULL, "password_hash" nvarchar(255) NOT NULL, "nombre" nvarchar(100) NOT NULL, "email" nvarchar(100) NOT NULL, "estado" nvarchar(1) NOT NULL, "id_centro_salud" int, CONSTRAINT "UQ_6ccff37176a6978449a99c82e10" UNIQUE ("username"), CONSTRAINT "UQ_2863682842e688ca198eb25c124" UNIQUE ("email"), CONSTRAINT "PK_dd52716c2652e0e23c15530c695" PRIMARY KEY ("id_usuario"))`);
        await queryRunner.query(`CREATE TABLE "programa_salud_oral" ("id_programa_salud_oral" int NOT NULL IDENTITY(1,1), "codigo" nvarchar(10) NOT NULL, "nombre" nvarchar(100) NOT NULL, "descripcion" nvarchar(255), "activo" nvarchar(1) NOT NULL, CONSTRAINT "UQ_e5703bad91241700e2a326c7e3b" UNIQUE ("codigo"), CONSTRAINT "PK_d8d414a51eacf49fbba44c6c54f" PRIMARY KEY ("id_programa_salud_oral"))`);
        await queryRunner.query(`CREATE TABLE "odontograma" ("id_odontograma" int NOT NULL IDENTITY(1,1), "pieza_dental" nvarchar(5) NOT NULL, "estado" nvarchar(50) NOT NULL, "observacion" text, "id_ficha_odontologica" int, CONSTRAINT "PK_9b0f91fedd9ba5da847512c4df5" PRIMARY KEY ("id_odontograma"))`);
        await queryRunner.query(`CREATE TABLE "radiografia" ("id_radiografia" int NOT NULL IDENTITY(1,1), "path" nvarchar(255) NOT NULL, "fecha_toma" datetime, "id_ficha_odontologica" int, CONSTRAINT "PK_16e88794ed65f1ab78bae204f2f" PRIMARY KEY ("id_radiografia"))`);
        await queryRunner.query(`CREATE TABLE "ficha_odontologica" ("id_ficha_odontologica" int NOT NULL IDENTITY(1,1), "fecha_control" datetime NOT NULL, "observacion" text, "id_paciente" int, "id_programa_salud_oral" int, "id_centro_salud" int, "id_usuario_responsable" int, CONSTRAINT "PK_b1ff5ca2daeb7d136683abe46ab" PRIMARY KEY ("id_ficha_odontologica"))`);
        await queryRunner.query(`CREATE TABLE "informe_pacam" ("id_informe_pacam" int NOT NULL IDENTITY(1,1), "fecha_informe" datetime NOT NULL, "total_beneficiario" int NOT NULL, "total_desembolso" numeric(10,2) NOT NULL, "id_programa_nutricional" int, CONSTRAINT "PK_2d5f91934a63ad271fa9b0f1715" PRIMARY KEY ("id_informe_pacam"))`);
        await queryRunner.query(`CREATE TABLE "programa_nutricional" ("id_programa_nutricional" int NOT NULL IDENTITY(1,1), "codigo" nvarchar(10) NOT NULL, "nombre" nvarchar(100) NOT NULL, "descripcion" nvarchar(255) NOT NULL, "activo" nvarchar(1) NOT NULL, CONSTRAINT "UQ_58b8111f76b2f3d2f964a621c72" UNIQUE ("codigo"), CONSTRAINT "PK_a36b36b2c14993a1b9c9d76cc5e" PRIMARY KEY ("id_programa_nutricional"))`);
        await queryRunner.query(`CREATE TABLE "control_desembolso" ("id_control_desembolso" int NOT NULL IDENTITY(1,1), "fecha_entrega" datetime NOT NULL, "cantidad_entregada" numeric(8,2) NOT NULL, "id_inscripcion_pacam" int, CONSTRAINT "PK_dd5d2f7a227194a8b020c749e61" PRIMARY KEY ("id_control_desembolso"))`);
        await queryRunner.query(`CREATE TABLE "inscripcion_pacam" ("id_inscripcion_pacam" int NOT NULL IDENTITY(1,1), "fecha_inscripcion" datetime NOT NULL, "estado" nvarchar(1) NOT NULL, "id_paciente" int, "id_programa_nutricional" int, "id_centro_salud" int, CONSTRAINT "PK_fdfb9cd10ca46000b8f9d79a6b9" PRIMARY KEY ("id_inscripcion_pacam"))`);
        await queryRunner.query(`CREATE TABLE "centro_salud" ("id_centro_salud" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(100) NOT NULL, "direccion" nvarchar(255) NOT NULL, "telefono" nvarchar(15) NOT NULL, "latitud" numeric(9,6), "longitud" numeric(9,6), CONSTRAINT "PK_988adb1f2a661ef63808f15cbd8" PRIMARY KEY ("id_centro_salud"))`);
        await queryRunner.query(`CREATE TABLE "historial_resultado" ("id_historial_resultado" int NOT NULL IDENTITY(1,1), "fecha_registro" datetime NOT NULL, "presion_sistolica" int, "presion_diastolica" int, "frecuencia_cardiaca" int, "glicemia" numeric(5,2), "peso" numeric(5,2), "talla" numeric(4,2), "imc" numeric(4,2), "observacion" text, "id_ficha_control" int, CONSTRAINT "PK_e9b9cdda61789a9a67305150817" PRIMARY KEY ("id_historial_resultado"))`);
        await queryRunner.query(`CREATE TABLE "estratificacion_riesgo" ("id_estratificacion_riesgo" int NOT NULL IDENTITY(1,1), "nivel_riesgo" nvarchar(20) NOT NULL, "motivo" nvarchar(255) NOT NULL, "fecha_asignacion" datetime NOT NULL, "id_ficha_control" int, "id_paciente" int, "usuario_responsable" int, CONSTRAINT "PK_bad655703ab54c720baa869d3d0" PRIMARY KEY ("id_estratificacion_riesgo"))`);
        await queryRunner.query(`CREATE TABLE "ficha_control" ("id_ficha_control" int NOT NULL IDENTITY(1,1), "fecha_control" datetime NOT NULL, "observacion" text, "id_paciente" int, "id_programa_control" int, "id_centro_salud" int, "id_usuario_responsable" int, CONSTRAINT "PK_356d57a8c291a26e488c0f032ac" PRIMARY KEY ("id_ficha_control"))`);
        await queryRunner.query(`CREATE TABLE "plan_intervencion" ("id_plan_intervencion" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(100) NOT NULL, "descripcion" nvarchar(255), "fecha_inicio" datetime, "fecha_fin" datetime, "id_familia" int, CONSTRAINT "PK_e5b68d3cde425a64224be87c61a" PRIMARY KEY ("id_plan_intervencion"))`);
        await queryRunner.query(`CREATE TABLE "factor_riesgo" ("id_factor_riesgo" int NOT NULL IDENTITY(1,1), "descripcion" nvarchar(255) NOT NULL, "id_familia" int, CONSTRAINT "PK_dc82b7f9f0bf382a1fa8f749507" PRIMARY KEY ("id_factor_riesgo"))`);
        await queryRunner.query(`CREATE TABLE "factor_protector" ("id_factor_protector" int NOT NULL IDENTITY(1,1), "descripcion" nvarchar(255) NOT NULL, "id_familia" int, CONSTRAINT "PK_fceb87ecceef55d1f7d75204c32" PRIMARY KEY ("id_factor_protector"))`);
        await queryRunner.query(`CREATE TABLE "familia" ("id_familia" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(100) NOT NULL, "fecha_creacion" datetime NOT NULL, CONSTRAINT "PK_773e10aa43e7f7e5cc57e4a5b2b" PRIMARY KEY ("id_familia"))`);
        await queryRunner.query(`CREATE TABLE "tipo_relacion" ("id_tipo_relacion" int NOT NULL IDENTITY(1,1), "descripcion" nvarchar(255) NOT NULL, CONSTRAINT "PK_f5de4d3346df2bdaed20b9152aa" PRIMARY KEY ("id_tipo_relacion"))`);
        await queryRunner.query(`CREATE TABLE "miembro_familiar" ("id_miembro_familiar" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(100) NOT NULL, "fecha_nacimiento" datetime, "genero" nvarchar(1), "id_familia" int, "id_tipo_relacion" int, "id_paciente" int, CONSTRAINT "PK_a5dd8c0c7649862b2b01f621bd4" PRIMARY KEY ("id_miembro_familiar"))`);
        await queryRunner.query(`CREATE TABLE "paciente" ("id_paciente" int NOT NULL IDENTITY(1,1), "direccion" nvarchar(100) NOT NULL, "rut" nvarchar(12) NOT NULL, "nombre" nvarchar(100) NOT NULL, "apellido_paterno" nvarchar(50) NOT NULL, "apellido_materno" nvarchar(50) NOT NULL, "fecha_nacimiento" datetime NOT NULL, "genero" nvarchar(1) NOT NULL, "telefono" nvarchar(15) NOT NULL, "centroSaludIdCentroSalud" int, CONSTRAINT "UQ_1c8ab2566bae114266d5b74d173" UNIQUE ("rut"), CONSTRAINT "PK_d30ab7a9e85df27360762d4325b" PRIMARY KEY ("id_paciente"))`);
        await queryRunner.query(`CREATE TABLE "alerta_inasistencia" ("id_alerta_inasistencia" int NOT NULL IDENTITY(1,1), "fecha_alerta" datetime NOT NULL, "motivo" nvarchar(255) NOT NULL, "id_registro_vacunacion" int, CONSTRAINT "PK_5b05c8d1d055357bb711a818f1e" PRIMARY KEY ("id_alerta_inasistencia"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_2b0ba21d14288f22e546affbdb" ON "alerta_inasistencia" ("id_registro_vacunacion") WHERE "id_registro_vacunacion" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "registro_vacunacion" ("id_registro_vacunacion" int NOT NULL IDENTITY(1,1), "fecha_aplicacion" datetime NOT NULL, "lote" nvarchar(50), "id_paciente" int, "id_vacuna" int, "id_calendario_vacuna" int, "id_centro_salud" int, "id_usuario_responsable" int, CONSTRAINT "PK_efbf5626ace5db86ff0eef1b192" PRIMARY KEY ("id_registro_vacunacion"))`);
        await queryRunner.query(`CREATE TABLE "vacuna" ("id_vacuna" int NOT NULL IDENTITY(1,1), "codigo" nvarchar(10) NOT NULL, "nombre" nvarchar(100) NOT NULL, "descripcion" nvarchar(255) NOT NULL, CONSTRAINT "UQ_2f62d02fa9963e6ab45435a52e8" UNIQUE ("codigo"), CONSTRAINT "PK_0f0a52e88770639740ac8606473" PRIMARY KEY ("id_vacuna"))`);
        await queryRunner.query(`CREATE TABLE "usuario_rol" ("id_usuario" int NOT NULL, "id_rol" int NOT NULL, CONSTRAINT "PK_cc28ffbe77be599168e1ec8670a" PRIMARY KEY ("id_usuario", "id_rol"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6adca3617fc69b2864e67196f2" ON "usuario_rol" ("id_usuario") `);
        await queryRunner.query(`CREATE INDEX "IDX_96d2a6ecb2ad0931416610845c" ON "usuario_rol" ("id_rol") `);
        await queryRunner.query(`ALTER TABLE "calendario_vacuna" ADD CONSTRAINT "FK_2dc494c4f4a56beeff572139daa" FOREIGN KEY ("id_vacuna") REFERENCES "vacuna"("id_vacuna") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_ff9e7737546c709c88c7b2e3f08" FOREIGN KEY ("id_centro_salud") REFERENCES "centro_salud"("id_centro_salud") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "odontograma" ADD CONSTRAINT "FK_033b8cea9f32c8cd763522c2c28" FOREIGN KEY ("id_ficha_odontologica") REFERENCES "ficha_odontologica"("id_ficha_odontologica") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "radiografia" ADD CONSTRAINT "FK_52959b8cadf599a61592add82e4" FOREIGN KEY ("id_ficha_odontologica") REFERENCES "ficha_odontologica"("id_ficha_odontologica") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" ADD CONSTRAINT "FK_240968e5d0228286d305a5f3f7e" FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" ADD CONSTRAINT "FK_0babef97a331d88af7c6e9449ce" FOREIGN KEY ("id_programa_salud_oral") REFERENCES "programa_salud_oral"("id_programa_salud_oral") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" ADD CONSTRAINT "FK_9ba4014c046d9903468e78dffce" FOREIGN KEY ("id_centro_salud") REFERENCES "centro_salud"("id_centro_salud") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" ADD CONSTRAINT "FK_4f49175cb28e2283efaf8adc078" FOREIGN KEY ("id_usuario_responsable") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_pacam" ADD CONSTRAINT "FK_e33569c9bf95e7b06cf76fa674e" FOREIGN KEY ("id_programa_nutricional") REFERENCES "programa_nutricional"("id_programa_nutricional") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control_desembolso" ADD CONSTRAINT "FK_c2acd274e611a6ad91a5b6e2fe6" FOREIGN KEY ("id_inscripcion_pacam") REFERENCES "inscripcion_pacam"("id_inscripcion_pacam") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion_pacam" ADD CONSTRAINT "FK_b96ca0cf7c55d6156320f8af8b3" FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion_pacam" ADD CONSTRAINT "FK_6b165ab286ce9b1aae6a1ec89e4" FOREIGN KEY ("id_programa_nutricional") REFERENCES "programa_nutricional"("id_programa_nutricional") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion_pacam" ADD CONSTRAINT "FK_156e9b723daeea8714745d3ea3b" FOREIGN KEY ("id_centro_salud") REFERENCES "centro_salud"("id_centro_salud") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_resultado" ADD CONSTRAINT "FK_cdf9895fb9ab415ec30caac24b8" FOREIGN KEY ("id_ficha_control") REFERENCES "ficha_control"("id_ficha_control") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estratificacion_riesgo" ADD CONSTRAINT "FK_39392564c708af3532d34f699b2" FOREIGN KEY ("id_ficha_control") REFERENCES "ficha_control"("id_ficha_control") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estratificacion_riesgo" ADD CONSTRAINT "FK_726424586e9f5913d4a3a5923bb" FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estratificacion_riesgo" ADD CONSTRAINT "FK_1cb08d0afb4f674586b974817d7" FOREIGN KEY ("usuario_responsable") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_control" ADD CONSTRAINT "FK_8ce483c98e6d3deecfd0d6b8135" FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_control" ADD CONSTRAINT "FK_ea9c0e4f569e40a46de0f43cb0f" FOREIGN KEY ("id_programa_control") REFERENCES "programa_control"("id_programa_control") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_control" ADD CONSTRAINT "FK_b1da48864119160ca21d1d5c936" FOREIGN KEY ("id_centro_salud") REFERENCES "centro_salud"("id_centro_salud") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ficha_control" ADD CONSTRAINT "FK_f237058c50b59bb365a27394d36" FOREIGN KEY ("id_usuario_responsable") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_intervencion" ADD CONSTRAINT "FK_408ea7005d15e75bb33a28ceb41" FOREIGN KEY ("id_familia") REFERENCES "familia"("id_familia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factor_riesgo" ADD CONSTRAINT "FK_dcc59bb4d5cbaea4419e2560f13" FOREIGN KEY ("id_familia") REFERENCES "familia"("id_familia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factor_protector" ADD CONSTRAINT "FK_7f43ab8ec8f78a5d75d15f804cc" FOREIGN KEY ("id_familia") REFERENCES "familia"("id_familia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "miembro_familiar" ADD CONSTRAINT "FK_90856aaa803fcbcae420d24df57" FOREIGN KEY ("id_familia") REFERENCES "familia"("id_familia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "miembro_familiar" ADD CONSTRAINT "FK_7edf2e7fc004357c35c2d0a1cc6" FOREIGN KEY ("id_tipo_relacion") REFERENCES "tipo_relacion"("id_tipo_relacion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "miembro_familiar" ADD CONSTRAINT "FK_e057197c8a3a7bc186f181bf3cd" FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paciente" ADD CONSTRAINT "FK_abe41e6cc37ba91f796fa06f1cd" FOREIGN KEY ("centroSaludIdCentroSalud") REFERENCES "centro_salud"("id_centro_salud") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerta_inasistencia" ADD CONSTRAINT "FK_2b0ba21d14288f22e546affbdba" FOREIGN KEY ("id_registro_vacunacion") REFERENCES "registro_vacunacion"("id_registro_vacunacion") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" ADD CONSTRAINT "FK_6e92213b6c9dfbc6560de529625" FOREIGN KEY ("id_paciente") REFERENCES "paciente"("id_paciente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" ADD CONSTRAINT "FK_0042b14a38a6cb574aa2bfa14c5" FOREIGN KEY ("id_vacuna") REFERENCES "vacuna"("id_vacuna") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" ADD CONSTRAINT "FK_fae7fb826fee64dbdbecb636e22" FOREIGN KEY ("id_calendario_vacuna") REFERENCES "calendario_vacuna"("id_calendario_vacuna") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" ADD CONSTRAINT "FK_3922a13ccb58cf4dbdc7f951dc3" FOREIGN KEY ("id_centro_salud") REFERENCES "centro_salud"("id_centro_salud") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" ADD CONSTRAINT "FK_27dcccf98096148e8718c7f2371" FOREIGN KEY ("id_usuario_responsable") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_6adca3617fc69b2864e67196f2a" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_96d2a6ecb2ad0931416610845cf" FOREIGN KEY ("id_rol") REFERENCES "rol"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_96d2a6ecb2ad0931416610845cf"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_6adca3617fc69b2864e67196f2a"`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" DROP CONSTRAINT "FK_27dcccf98096148e8718c7f2371"`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" DROP CONSTRAINT "FK_3922a13ccb58cf4dbdc7f951dc3"`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" DROP CONSTRAINT "FK_fae7fb826fee64dbdbecb636e22"`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" DROP CONSTRAINT "FK_0042b14a38a6cb574aa2bfa14c5"`);
        await queryRunner.query(`ALTER TABLE "registro_vacunacion" DROP CONSTRAINT "FK_6e92213b6c9dfbc6560de529625"`);
        await queryRunner.query(`ALTER TABLE "alerta_inasistencia" DROP CONSTRAINT "FK_2b0ba21d14288f22e546affbdba"`);
        await queryRunner.query(`ALTER TABLE "paciente" DROP CONSTRAINT "FK_abe41e6cc37ba91f796fa06f1cd"`);
        await queryRunner.query(`ALTER TABLE "miembro_familiar" DROP CONSTRAINT "FK_e057197c8a3a7bc186f181bf3cd"`);
        await queryRunner.query(`ALTER TABLE "miembro_familiar" DROP CONSTRAINT "FK_7edf2e7fc004357c35c2d0a1cc6"`);
        await queryRunner.query(`ALTER TABLE "miembro_familiar" DROP CONSTRAINT "FK_90856aaa803fcbcae420d24df57"`);
        await queryRunner.query(`ALTER TABLE "factor_protector" DROP CONSTRAINT "FK_7f43ab8ec8f78a5d75d15f804cc"`);
        await queryRunner.query(`ALTER TABLE "factor_riesgo" DROP CONSTRAINT "FK_dcc59bb4d5cbaea4419e2560f13"`);
        await queryRunner.query(`ALTER TABLE "plan_intervencion" DROP CONSTRAINT "FK_408ea7005d15e75bb33a28ceb41"`);
        await queryRunner.query(`ALTER TABLE "ficha_control" DROP CONSTRAINT "FK_f237058c50b59bb365a27394d36"`);
        await queryRunner.query(`ALTER TABLE "ficha_control" DROP CONSTRAINT "FK_b1da48864119160ca21d1d5c936"`);
        await queryRunner.query(`ALTER TABLE "ficha_control" DROP CONSTRAINT "FK_ea9c0e4f569e40a46de0f43cb0f"`);
        await queryRunner.query(`ALTER TABLE "ficha_control" DROP CONSTRAINT "FK_8ce483c98e6d3deecfd0d6b8135"`);
        await queryRunner.query(`ALTER TABLE "estratificacion_riesgo" DROP CONSTRAINT "FK_1cb08d0afb4f674586b974817d7"`);
        await queryRunner.query(`ALTER TABLE "estratificacion_riesgo" DROP CONSTRAINT "FK_726424586e9f5913d4a3a5923bb"`);
        await queryRunner.query(`ALTER TABLE "estratificacion_riesgo" DROP CONSTRAINT "FK_39392564c708af3532d34f699b2"`);
        await queryRunner.query(`ALTER TABLE "historial_resultado" DROP CONSTRAINT "FK_cdf9895fb9ab415ec30caac24b8"`);
        await queryRunner.query(`ALTER TABLE "inscripcion_pacam" DROP CONSTRAINT "FK_156e9b723daeea8714745d3ea3b"`);
        await queryRunner.query(`ALTER TABLE "inscripcion_pacam" DROP CONSTRAINT "FK_6b165ab286ce9b1aae6a1ec89e4"`);
        await queryRunner.query(`ALTER TABLE "inscripcion_pacam" DROP CONSTRAINT "FK_b96ca0cf7c55d6156320f8af8b3"`);
        await queryRunner.query(`ALTER TABLE "control_desembolso" DROP CONSTRAINT "FK_c2acd274e611a6ad91a5b6e2fe6"`);
        await queryRunner.query(`ALTER TABLE "informe_pacam" DROP CONSTRAINT "FK_e33569c9bf95e7b06cf76fa674e"`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" DROP CONSTRAINT "FK_4f49175cb28e2283efaf8adc078"`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" DROP CONSTRAINT "FK_9ba4014c046d9903468e78dffce"`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" DROP CONSTRAINT "FK_0babef97a331d88af7c6e9449ce"`);
        await queryRunner.query(`ALTER TABLE "ficha_odontologica" DROP CONSTRAINT "FK_240968e5d0228286d305a5f3f7e"`);
        await queryRunner.query(`ALTER TABLE "radiografia" DROP CONSTRAINT "FK_52959b8cadf599a61592add82e4"`);
        await queryRunner.query(`ALTER TABLE "odontograma" DROP CONSTRAINT "FK_033b8cea9f32c8cd763522c2c28"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_ff9e7737546c709c88c7b2e3f08"`);
        await queryRunner.query(`ALTER TABLE "calendario_vacuna" DROP CONSTRAINT "FK_2dc494c4f4a56beeff572139daa"`);
        await queryRunner.query(`DROP INDEX "IDX_96d2a6ecb2ad0931416610845c" ON "usuario_rol"`);
        await queryRunner.query(`DROP INDEX "IDX_6adca3617fc69b2864e67196f2" ON "usuario_rol"`);
        await queryRunner.query(`DROP TABLE "usuario_rol"`);
        await queryRunner.query(`DROP TABLE "vacuna"`);
        await queryRunner.query(`DROP TABLE "registro_vacunacion"`);
        await queryRunner.query(`DROP INDEX "REL_2b0ba21d14288f22e546affbdb" ON "alerta_inasistencia"`);
        await queryRunner.query(`DROP TABLE "alerta_inasistencia"`);
        await queryRunner.query(`DROP TABLE "paciente"`);
        await queryRunner.query(`DROP TABLE "miembro_familiar"`);
        await queryRunner.query(`DROP TABLE "tipo_relacion"`);
        await queryRunner.query(`DROP TABLE "familia"`);
        await queryRunner.query(`DROP TABLE "factor_protector"`);
        await queryRunner.query(`DROP TABLE "factor_riesgo"`);
        await queryRunner.query(`DROP TABLE "plan_intervencion"`);
        await queryRunner.query(`DROP TABLE "ficha_control"`);
        await queryRunner.query(`DROP TABLE "estratificacion_riesgo"`);
        await queryRunner.query(`DROP TABLE "historial_resultado"`);
        await queryRunner.query(`DROP TABLE "centro_salud"`);
        await queryRunner.query(`DROP TABLE "inscripcion_pacam"`);
        await queryRunner.query(`DROP TABLE "control_desembolso"`);
        await queryRunner.query(`DROP TABLE "programa_nutricional"`);
        await queryRunner.query(`DROP TABLE "informe_pacam"`);
        await queryRunner.query(`DROP TABLE "ficha_odontologica"`);
        await queryRunner.query(`DROP TABLE "radiografia"`);
        await queryRunner.query(`DROP TABLE "odontograma"`);
        await queryRunner.query(`DROP TABLE "programa_salud_oral"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "rol"`);
        await queryRunner.query(`DROP TABLE "programa_control"`);
        await queryRunner.query(`DROP TABLE "calendario_vacuna"`);
    }

}
