apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-service
  namespace: proyecto-gps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinical-service
  template:
    metadata:
      labels:
        app: clinical-service
    spec:
      containers:
      - name: clinical-service
        image: johnsondavisv45/clinical-service:latest
        ports:
        - containerPort: 3002
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 100%
          maxUnavailable: 100%
