apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: proyecto-gps
  annotations:
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: johnsondavisv45/core-service:latest
        ports:
        - containerPort: 3001
