apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: proyecto-gps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: johnsondavisv45/frontend:latest
        ports:
        - containerPort: 4200
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
