apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service
  namespace: proyecto-gps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
    spec:
      containers:
      - name: nutrition-service
        image: johnsondavisv45/nutrition-service:latest
        ports:
        - containerPort: 3001
