apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: v1
kind: Service
metadata:
  name: clinical-service
  namespace: proyecto-gps
spec:
  selector:
    app: clinical-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
