apiVersion: v1
kind: Service
metadata:
  name: clinical-service-metrics
  namespace: proyecto-gps
  labels:
    app: clinical-service
    prometheus: targets
spec:
  selector:
    app: clinical-service
  ports:
    - name: metrics
      port: 3002
      targetPort: 3002
