apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: proyecto-gps
spec:
  selector:
    app: core-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
