apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-gps
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: johnsondavisv45/frontend:latest
          ports:
            - containerPort: 4200
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
