apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: v1
kind: Service
metadata:
  name: nutrition-service
  namespace: proyecto-gps
spec:
  selector:
    app: nutrition-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
