apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: v1
kind: Service
metadata:
  name: odonto-service
  namespace: proyecto-gps
spec:
  selector:
    app: odonto-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
