apiVersion: v1
kind: Service
metadata:
  name: odonto-service-metrics
  namespace: proyecto-gps
  labels:
    app: odonto-service
    prometheus: targets
spec:
  selector:
    app: odonto-service
  ports:
    - name: metrics
      port: 3004
      targetPort: 3004
