apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-gps
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3005"
    spec:
      containers:
        - name: patient-service
          image: johnsondavisv45/patient-service:latest
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 3005
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
