apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-gps
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: proyecto-gps
spec:
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
