apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service-metrics
  namespace: proyecto-gps
  labels:
    app: pharmacy-service
    prometheus: targets
spec:
  selector:
    app: pharmacy-service
  ports:
    - name: metrics
      port: 3006
      targetPort: 3006
