apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proyecto-gps-apis
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - proyecto-gps
  selector:
    matchLabels:
      prometheus: targets
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1s

