apiVersion: v1
kind: Service
metadata:
  name: vaccination-service
  namespace: proyecto-gps
spec:
  selector:
    app: vaccination-service
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
