name: Build & Push Odonto Service

on:
  push:
    branches:
      - main
    paths:
      - backend/apps/odonto-service/**
      - backend/apps/odonto-service/package*.json
  pull_request:
    branches:
      - main
    paths:
      - backend/apps/odonto-service/**
      - backend/apps/odonto-service/package*.json
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build & Push Odonto Service
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/odonto-service:latest
          docker build \
            -f backend/apps/odonto-service/Dockerfile \
            -t $IMAGE \
            backend/apps/odonto-service
          docker push $IMAGE