name: Build & Push Patient Service

on:
  push:
    branches:
      - main
    paths:
      - backend/apps/patient-service/**
      - backend/package*.json
      - backend/nest-cli.json
      - backend/tsconfig*.json
      - backend/libs/**
  pull_request:
    branches:
      - main
    paths:
      - backend/apps/patient-service/**
      - backend/package*.json
      - backend/nest-cli.json
      - backend/tsconfig*.json
      - backend/libs/**
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build & Push Patient Service
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/patient-service:latest
          docker build \
            -f backend/apps/patient-service/Dockerfile \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DB_USER=${{ secrets.DB_USER }} \
            --build-arg DB_PASS=${{ secrets.DB_PASS }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            --build-arg DB_POOL_MODE=${{ secrets.DB_POOL_MODE }} \
            --build-arg PORT_PATIENT=${{ secrets.PORT_PATIENT }} \
            --build-arg SCHEMA_PATIENT=${{ secrets.SCHEMA_PATIENT }} \
            -t $IMAGE \
            backend
          docker push $IMAGE

      - name: Trigger Kubernetes Redeploy
        run: |
          curl -X POST https://kubernetes-redeploy.proyecto-uni.online/redeploy/patient-service \
            -H "Authorization: Bearer ${{ secrets.KUBE_TOKEN }}" \
            -f